spring:
  docker:
    compose:
      enabled: false
  data:
    mongodb:
      host: localhost
      database: secret-santa-app
      username: root
      password: secret
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: localhost
    username: root
    password: secret

