name: Build project

on:
  push:
    branches:
      - 'main'
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened

jobs:
  build-project-job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle build
        run: ./gradlew build


